### PR TITLE
Letsencrypt

### PR DESCRIPTION
**Pull request by DanyThePuma**
1 - Remove ")" after $opt_mail causing email recognition issue while running script. 
2 - Update DESCRIPTION and DESCRIPTION_GER, to avoid packaging error due to "(CA)" and "(ISRG)".

### CODE REVIEW

**Comment by DanyThePuma** [comment]
Yes, it's another solution. Maybe more simple with quotation marks on whole description to avoid antislash for each ( or ) ?

**Comment by jekkos** [comment]
I'm struggling to get this package compile for bromolow-5.2 (probllem with native-python install). Are there any packages available for download for this spk? I'm eager to give this a try.

**Comment by lexyan** [comment]
@jekkos : try to compile python in native directory before trying to cross-compile letsencrypt

**Comment by jekkos** [comment]
Indeed that seems to solve the issue.. I this answer on the spksrc issue tracker as well today.

**Comment by jekkos** [comment]
Time to test the package now :+1:

**Comment by jekkos** [comment]
Currently facing another issue during install of the package

pkgtool.cpp:1338 /volume3/@tmp/569E94AC17BE842C//WIZARD_UIFILES/install_uifile_enu: * Line 13, Column 29

did you have any trouble with this? This error line from synology log seems to refer to the regex validation in the setup file itself. The package manager bails out with a 'This package is not supported on the platform of Diskstation' error.

**Comment by jekkos** [comment]
Ok I pulled in latest changes from spksrc and now the install is working fine. How does the package exactly work? How does it determine which certificate it should refresh? Should the initial setup be done through the command line?

**Comment by lexyan** [comment]
You can launch manually the script (letsencrypt-synology.sh) from the command line or wait for cron to automatically refresh certificates each month the 15 at 00:00.

**Comment by jekkos** [comment]
Ok but if there are no certs installed yet, it will automatically determine which dns names are in use and request the certs from letsencrypt? Or do I have to make a csr in the specified script folder first to have it signed by let's encrypt?

**Comment by lexyan** [comment]
No, the script parse the vhost file and see which domain respond in dns. then it ask letsencrypt server certificate for those domain and install it

**Pull request merged**
